namespace TypeSafeAI.Tests;

/// <summary>
/// The request and response bodies printed verbatim in the TypeSafe documentation.
/// </summary>
/// <remarks>
/// These are transcribed from the docs rather than generated by the SDK, so that the serialization
/// tests compare the SDK against the published contract instead of against itself.
/// </remarks>
internal static class Fixtures
{
    /// <summary>The minimal noul request from the API reference.</summary>
    public const string MinimalNoulRequest = """
        {
          "state": "Help! My payouts have been failing for 3 days.",
          "model": "jev-latest",
          "questions": {
            "is_urgent": {
              "type": "noul",
              "instructions": "Does this convey urgency?"
            }
          }
        }
        """;

    /// <summary>The noul request with criteria from the API reference.</summary>
    public const string NoulWithCriteriaRequest = """
        {
          "state": "Help! My payouts have been failing for 3 days.",
          "model": "jev-latest",
          "questions": {
            "is_urgent": {
              "type": "noul",
              "instructions": "Does this convey urgency?",
              "criteria": {
                "true": "Explicitly time-sensitive",
                "false": "No urgency expressed"
              }
            }
          }
        }
        """;

    /// <summary>The choice request from the API reference.</summary>
    public const string ChoiceRequest = """
        {
          "state": "Help! My payouts have been failing for 3 days.",
          "model": "jev-latest",
          "questions": {
            "department": {
              "type": "choice",
              "instructions": "Which team should handle this?",
              "criteria": {
                "billing": "Payments, invoicing, refunds",
                "technical": "Bugs, outages, integrations",
                "sales": "Pricing, upgrades, new accounts"
              }
            }
          }
        }
        """;

    /// <summary>The score request from the API reference.</summary>
    public const string ScoreRequest = """
        {
          "state": "Help! My payouts have been failing for 3 days.",
          "model": "jev-latest",
          "questions": {
            "frustration": {
              "type": "score",
              "instructions": "How frustrated is the customer?",
              "criteria": ["Calm", "Frustrated", "Very angry"]
            }
          }
        }
        """;

    /// <summary>The noul response from the API reference.</summary>
    public const string NoulResponse = """
        {
          "model": "jev-latest",
          "answers": {
            "is_urgent": {
              "type": "noul",
              "noul": 0.92
            }
          },
          "usage": { "input_tokens": 312, "output_tokens": 48 }
        }
        """;

    /// <summary>The choice response from the API reference.</summary>
    public const string ChoiceResponse = """
        {
          "model": "jev-latest",
          "answers": {
            "department": {
              "type": "choice",
              "choice": "technical",
              "probabilities": { "billing": 0.08, "technical": 0.85, "sales": 0.07 },
              "confidence": 0.82
            }
          },
          "usage": { "input_tokens": 312, "output_tokens": 48 }
        }
        """;

    /// <summary>The score response from the API reference.</summary>
    public const string ScoreResponse = """
        {
          "model": "jev-latest",
          "answers": {
            "frustration": {
              "type": "score",
              "score": 1.6,
              "legend": { "0": "Calm", "1": "Frustrated", "2": "Very angry" },
              "probabilities": { "0": 0.05, "1": 0.3, "2": 0.65 },
              "confidence": 0.78
            }
          },
          "usage": { "input_tokens": 312, "output_tokens": 48 }
        }
        """;

    /// <summary>
    /// A three-score response with the fractional values printed in the Score documentation.
    /// </summary>
    public const string ThreeScoreResponse = """
        {
          "model": "jev-1.13.0",
          "answers": {
            "severity": {
              "type": "score",
              "score": 1.24,
              "legend": { "0": "low", "1": "medium", "2": "high" },
              "probabilities": { "0": 0.12, "1": 0.52, "2": 0.36 },
              "confidence": 0.63
            },
            "frustration": {
              "type": "score",
              "score": 1.45,
              "legend": { "0": "calm", "1": "frustrated", "2": "very angry" },
              "probabilities": { "0": 0.0, "1": 0.55, "2": 0.45 },
              "confidence": 0.33
            },
            "reproducibility": {
              "type": "score",
              "score": 3.0,
              "legend": { "0": "none", "1": "vague", "2": "partial", "3": "exact" },
              "probabilities": { "0": 0.0, "1": 0.0, "2": 0.0, "3": 1.0 },
              "confidence": 1.0
            }
          },
          "usage": { "input_tokens": 900, "output_tokens": 120 }
        }
        """;

    /// <summary>
    /// A score response whose legend echoes structured levels, as the structure documentation shows.
    /// </summary>
    /// <remarks>
    /// This is the case that breaks any implementation that types legend values as strings.
    /// </remarks>
    public const string StructuredLegendResponse = """
        {
          "model": "jev-latest",
          "answers": {
            "amount_due": {
              "type": "score",
              "score": 1.0,
              "legend": {
                "0": { "label": "small", "max_usd": 1000 },
                "1": { "label": "medium", "max_usd": 10000 },
                "2": ["large", "enterprise"]
              },
              "probabilities": { "0": 0.1, "1": 0.6, "2": 0.3 },
              "confidence": 0.5
            }
          },
          "usage": { "input_tokens": 100, "output_tokens": 20 }
        }
        """;

    /// <summary>An error body for an application-level failure.</summary>
    public const string ApplicationErrorBody = """
        {"detail":{"error_type":"authentication_error","message":"Cannot authenticate with the server. Please check your API key and try again."}}
        """;

    /// <summary>An error body for a framework-level failure, where <c>detail</c> is a bare string.</summary>
    public const string FrameworkErrorBody = """{"detail":"Not Found"}""";

    /// <summary>An error body that is not JSON at all.</summary>
    public const string NonJsonErrorBody = "<html><body>502 Bad Gateway</body></html>";
}
