<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTrimmable>false</IsTrimmable>
    <IsAotCompatible>false</IsAotCompatible>
    <EnablePackageValidation>false</EnablePackageValidation>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
    <RootNamespace>TypeSafeAI.Samples</RootNamespace>
    <AssemblyName>TypeSafe.Sdk.Samples</AssemblyName>
    <UserSecretsId>typesafe-sdk-samples</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TypeSafe.Sdk\TypeSafe.Sdk.csproj" />
  </ItemGroup>

</Project>
